<?php
$data = array (
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '高荣是',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '18',
    'name' => '高荣是',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '荣实施',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => '荣实施',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '平板电脑',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '平板电脑',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '艾派德',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '艾派德',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '艾派德6',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '15',
    'name' => '艾派德6',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '艾派德5',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 2,
    'id' => '16',
    'name' => '艾派德5',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '小小艾派德',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '17',
    'name' => '小小艾派德',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '小米平板',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '小米平板',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '玻璃',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '1',
    'level' => 0,
    'id' => '10',
    'name' => '玻璃',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '分类一',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => '分类一',
  ),
);
?>